### ISSUE TITLE
Discussion on unit testing framework

### ISSUE THREAD

**Issue by edmistond** [DevChatter/Smilodon#13]
Since unit testing is good practice, it's probably best to start early before there's a lot of code in place.

Are there general preferences for unit test frameworks and ancillary libraries? I generally favor, and have had good results, with a combination of:

* XUnit
* NSubstitute
* AutoFixture
* Fluent Assertions

Those seem to be pretty common choices I see these days; the only thing I would note is that NSubstitute can be a little persnickety about mocking/stubbing some methods, so Rhino or Moq are always an option too.

I can take a cut at adding `test/` alongside the `src/` directory and setting up a basic unit test project, if desired.

**Comment by kirkbrauer** [comment]
I've been using Moq recently, and I absolutely love the way it interacts with all the other tools you mentioned. However, I do sometimes find it a bit confusing when setting up complex mocks.

**Comment by benrick** [comment]
Awesome suggestions.

 I believe our build process attempts to run the test projects though there currently are none. 

Regarding the suggested options, I'm always in favor of choosing frameworks that have a good threshold of users, which all of these libraries have.

For the testing framework itself, XUnit or NUnit would be the choices I would recommend. I'd be fine with NSubstitute, Moq, or another mocking framework. Yeah, AutoFixture or similar will help. I also use Fluent Assertions, but I'd be OK if others wanted Shouldly.

**Comment by benrick** [comment]
I usually have separate projects for UnitTests, IntegrationTests, UITests, etc.

I don't want to just force the way I do things into the project though. What are everyone else's thoughts?

**Comment by kirkbrauer** [comment]
@edmistond I'm onboard with Moq, I think that along with Fluent Assertions, AutoFixture, and XUnit are pretty much the de-facto standard in new open source .NET projects these days.

**Comment by benrick** [comment]
> ```
> ├── src
> │   ├── ActivityPub
> │   └── WebFinger
> └── test
>     ├── ActivityPub.Tests
>     ├── ActivityPub.IntegrationTests
>     └── WebFinger.Tests
> ```

I'll need to recheck the API for Mastodon, but I thought that ActivityPub and Webfinger get served through the same API (could be wrong). We can absolutely separate the projects, since they're different specs and have the API itself just pull from a ClassLib containing corresponding spec.

**Comment by kirkbrauer** [comment]
@benrick yeah, I just checked the docs on that as well. 

I think it's best to have a lot of class library-only projects and a single, central host project that can act as the primary host.

Perhaps we could have something like `ActivityPub.Domain` and `ActivityPub.WebAPI`, which could hold the domain models and the API endpoints respectively. All of that could be tied together in a entry point project like `Similodon.Host` or something along those lines.

**Comment by kirkbrauer** [comment]
For reference, this is currently what one of my solutions looks like, each subdomain has it's own solution folder to keep everything super organized:
<img width="306" alt="Screen Shot 2022-11-21 at 22 30 16" src="https://user-images.githubusercontent.com/14915766/203214486-a2bef917-2f5b-485f-8fb4-f7662a23bb05.png">

**Comment by kirkbrauer** [comment]
@benrick yup, checking the docs, I believe Webfinger is supposed to be capitalized as WebFinger, but that's just nitpicking 😉
