### ISSUE TITLE
Switch to Central Package Management (CPM) for solution

### ISSUE THREAD

**Issue by kirkbrauer** [DevChatter/Smilodon#15]
**Is your feature request related to a problem? Please describe.**
Since this solution is growing to contain multiple projects, it is probably best to setup Central Package Management, so all package versions can be handled on the solution level.

**Describe the solution you'd like**
We need to create a `Directory.Packages.props` file and define all the package versions. 

Each project can then just include a `<PackageReference Include="Package" />` to reference that package.

**Additional context**
[Central Package Management on Microsoft Docs](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management)

**Comment by benrick** [comment]
Yeah, I agree with this 100%. It'll pay dividends whether we stick to `/src` and `/test` as the top level or put tests beside the ClassLib they test.

**Comment by kirkbrauer** [comment]
I'll make a PR to add these config files once we merge #14.
