### ISSUE TITLE
Duplicate package sources warning on macOS

### ISSUE THREAD

**Issue by edmistond** [DevChatter/Smilodon#20]
**Describe the bug**
I pulled the project down to my M1 MBP to verify that things ran correctly. JetBrains Rider would not load dependencies and threw an error. `dotnet build` on the command line worked, but threw warnings for the three projects in `src/`:

`/Users/edmistond/projects/Smilodon/test/WebApp.Test/WebApp.Test.csproj : warning NU1507: There are 2 package sources defined in your configuration. When using central package management, please map your package sources with package source mapping (https://aka.ms/nuget-package-source-mapping) or specify a single package source. The following sources are defined: nuget.org, /usr/local/share/dotnet/library-packs [/Users/edmistond/projects/Smilodon/Smilodon.sln]`

**Expected behavior**
Project should build cleanly regardless of platform.

**Additional context**
I tested adding a nuget.config to my project root directory which simplify specifies nuget.org as the default wildcard package source, and this resolved the issue. I haven't opened the PR for it yet because I haven't had time to pull my fix branch down to my Windows desktop to ensure it doesn't break anything there. Wanted to make note of the issue and have something to file the PR against when I submit it.

Probably won't be able to get to this until Friday or Saturday. You can see my nuget.config here: https://github.com/edmistond/Smilodon/commit/32eecbc30d3d5e364a6829b030cc498684728a6c

**Comment by benrick** [comment]
Good catch. This reminds me that we need to matrix the PR build as well.

I think we can define our package source to avoid this (probably what's in
your link).

**Comment by benrick** [comment]
Good catch. This reminds me that we need to matrix the PR build as well.

Your fix is exactly what we need to avoid this warning. I think we'd have gotten this regardless of operating system just from having a second source.

**Comment by kirkbrauer** [comment]
This is interesting, I did the initial setup for the Central Package Management on macOS Intel with .NET 7. 

One other compatability issue I also ran into was some files using CRLF and others using LF line endings. We might need to add a `.gitattributes` file to specify LF line endings for all commits
