### ISSUE TITLE
Consider Telemetry and Instrumentation

### ISSUE THREAD

**Issue by edmistond** [DevChatter/Smilodon#32]
**Is your feature request related to a problem? Please describe.**
While not wanting to prematurely optimize, good telemetry is invaluable both in debugging and in operating software generally. Accordingly, it would be good to give some thought now to how we'd like to implement this so we don't have to go back and retrofit a bunch of it after-the-fact.

**Describe the solution you'd like**
An OpenTelemetry-based solution seems best since it is an emerging industry standard and should allow instance operators to integrate with hosted/paid solutions like HoneyComb as well as running a local collector setup for debugging purposes.

**Describe alternatives you've considered**
Console/file-based logging, or a more dedicated solution like Seq or Azure App Insights could be an option, but get expensive quickly. It is possible to run a basic self-hosted OT collector via Docker Compose. I may be wrong but I believe those solutions are beginning to support OpenTelemetry anyway.

**Comment by benrick** [comment]
Agreed 100% on adding it before we get too much built. Also OT is a good choice that we can easily support in dotnet!

I'm willing to bet that most of the cloud solutions will support OT eventually if they don't already.

**Comment by edmistond** [comment]
Sounds good - I'll start putting something together to add instrumentation to the WebApp project for starters. If I don't run into any problems getting that set up I'll se about adding some "how do I run telemetry locally" documentation.

This also opens up yet another can of worms 😀 - how we want to handle configuration. That should probably be a separate issue to discuss, but I generally like strongly-typed configs with validation that won't allow the app to start up if any required config is missing - it's saved me from some real pain a few times. However, don't have to start with that initially.
