### ISSUE TITLE
Contribution Instructions

### ISSUE THREAD

**Issue by benrick** [DevChatter/Smilodon#5]
We need to grab a quick set of instructions for new contributors, so that we can offer them some guidance in how they can contribute to the project.

Don't put a lot of effort into an initial one. Just find a simple one from the Internet (template, example, or from another project).

**Comment by benrick** [comment]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by FrankFK** [comment]
I'll take a look on it and make a suggestion as a pull request

**Comment by FrankFK** [comment]
@benrick Can you invite me to be a collaborator, please? Then I can create a branch for it.

**Comment by benrick** [comment]
Hi @FrankFK ! Glad you made it over!

You should be able to fork a copy of the repository, clone the fork locally,  and make a branch there. Then you can send a pull request to this repository with your changes. 

This tutorial looks good: https://jarv.is/notes/how-to-pull-request-fork-github/
